CREATE TABLE PRODUCT(
	ProductID INT PRIMARY KEY,
	CategoryID INT,
	Productname VARCHAR(20),
	Description VARCHAR(50));

CREATE TABLE PRODUCT_CATEGORY(
	CategoryID INT PRIMARY KEY,
	Name VARCHAR(20),
	Description VARCHAR(50));

CREATE TABLE SUPPLIER(
	SupplierVAT INT,
	SupplierName VARCHAR(20),
	Address VARCHAR(20),
	Phone INT,
	Email VARCHAR(50));

CREATE TABLE SUPPLY(
	InvoiceID INT
	SupplierVAT INT,
	Date VARCHAR(20));

CREATE TABLE PRODUCT_SUPPLY(
	InvoiceID INT,
	ProductID INT,
	Quantity INT,
	Value DOUBLE);

CREATE TABLE SALE(
	SaleID INT,
	Date VARCHAR(20));

CREATE TABLE SALE_OF_PRODUCT(
	SaleID INT,
	ProductID INT,
	Quantity INT,
	Value INT);

CREATE TABLE PRODUCT_RETURN(
	SaleID INT,
	ProductID INT
	Date VARCHAR(20),
	Quantity INT);

CREATE TABLE STOCK(
	ProductID INT,
	Quantity INT);