-- 
CREATE TABLE PRODUCT_CATEGORY(
	CategoryID INT PRIMARY KEY,
	Name VARCHAR(100),
	Description VARCHAR(100));
-- 
CREATE TABLE PRODUCT(
	ProductID INT PRIMARY KEY,
	CategoryID INT,
	Productname VARCHAR(100),
	Description VARCHAR(100),
	FOREIGN KEY (CategoryID));
-- 
CREATE TABLE SUPPLIER(
	SupplierVAT INT PRIMARY KEY,
	SupplierName VARCHAR(100),
	Address VARCHAR(100),
	Phone INT,
	Email VARCHAR(100));
-- 
CREATE TABLE SUPPLY(
	InvoiceID INT PRIMARY KEY,
	SupplierVAT INT,
	Date DATE,
	(FOREIGN KEY (SupplierVAT)));
-- 
CREATE TABLE PRODUCT_SUPPLY(
	InvoiceID INT,
	ProductID INT,
	Quantity INT,
	Value DECIMAL,
	PRIMARY KEY (InvoiceID,ProductID),
	FOREIGN KEY (ProductID),
	FOREIGN KEY (InvoiceID));
-- 
CREATE TABLE SALE(
	SaleID INT PRIMARY KEY,
	Date DATE);
-- 
CREATE TABLE SALE_OF_PRODUCT(
	SaleID INT ,
	ProductID INT,
	Quantity INT,
	Value DECIMAL,
	PRIMARY KEY (SaleID, ProductID),
	FOREIGN KEY (SaleID),
	FOREIGN KEY (ProductID));
-- 
CREATE TABLE PRODUCT_RETURN(
	SaleID INT,
	ProductID INT,
	Date DATE,
	Quantity INT,
	PRIMARY KEY (SaleID, ProductID, Quantity),
	FOREIGN KEY (SaleID),
	FOREIGN KEY (ProductID));
-- 
CREATE TABLE STOCK(
	ProductID INT PRIMARY KEY,
	Quantity INT);