-- 
CREATE TABLE PRODUCT(
	ProductID INT PRIMARY KEY,
	CategoryID INT,
	Productname VARCHAR(20),
	Description VARCHAR(50)),
	FOREIGN KEY (CategoryID) REFERENCES PRODUCT_CATEGORY;
-- 
CREATE TABLE PRODUCT_CATEGORY(
	CategoryID INT PRIMARY KEY,
	Name VARCHAR(20),
	Description VARCHAR(50));
-- 
CREATE TABLE SUPPLIER(
	SupplierVAT INT PRIMARY KEY,
	SupplierName VARCHAR(20),
	Address VARCHAR(20),
	Phone INT,
	Email VARCHAR(50));
-- 
CREATE TABLE SUPPLY(
	InvoiceID INT PRIMARY KEY,
	SupplierVAT INT,
	Date DATE,
	FOREIGN KEY (SupplierVAT) REFERENCES SUPPLIER);
-- 
CREATE TABLE PRODUCT_SUPPLY(
	InvoiceID INT,
	ProductID INT,
	Quantity INT,
	Value DECIMAL,
	PRIMARY KEY (InvoiceID,ProductID),
	FOREIGN KEY (ProductID) REFERENCES PRODUCT,
	FOREIGN KEY (InvoiceID) REFERENCES SUPPLY);
-- 
CREATE TABLE SALE(
	SaleID INT PRIMARY KEY,
	Date VARCHAR(20));
-- 
CREATE TABLE SALE_OF_PRODUCT(
	SaleID INT PRIMARY KEY,
	ProductID INT,
	Quantity INT,
	Value INT,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT);
-- 
CREATE TABLE PRODUCT_RETURN(
	SaleID INT,
	ProductID INT
	Date DATE,
	Quantity INT,
	PRIMARY KEY (SaleID, ProductID),
	FOREIGN KEY (SaleID) REFERENCES SALE,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT);
-- 
CREATE TABLE STOCK(
	ProductID INT PRIMARY KEY,
	Quantity INT);